/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.File;
import java.util.Map;
import javax.servlet.ServletRegistration;
import javax.servlet.http.HttpServlet;

import org.apache.catalina.Context;
import org.apache.catalina.startup.Tomcat;


public class App {
    public static void main(String[] args) throws Exception {
        String root = new File(".").getAbsolutePath();

        String baseDir = root + File.separatorChar + "temp";

        int webPort = 18080;

        Tomcat tomcat = new Tomcat();
        tomcat.setPort(webPort);

        tomcat.setBaseDir(baseDir);
        tomcat.setPort(webPort);

        Context context = tomcat.addContext("/", baseDir);

        HttpServlet board = new BoardServlet();

        // http://localhost:18080/board?mode=callList
        tomcat.addServlet("/", "board", board);
        context.addServletMappingDecoded("/board", "board");

        tomcat.getConnector();
        tomcat.start();
        tomcat.getServer().await();
    }
}
